# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: utf8
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-poolingp
  pool: 5

development:
  <<: *default
  # database: ism_development
  database: instorem_server
  username: postgresql
  password:
  host: localhost

production:
  <<: *default
  # database: ism_development
  database: instorem_server
  username: postgresql
  password:
  host: localhost

# heroku pgbackups:capture --app in-store-marketing && curl -o latest.dump `heroku pgbackups:url --app in-store-marketing` && rake db:drop db:create && pg_restore --verbose --clean --no-acl --no-owner -h localhost -U postgresql -d instorem_server instorem_server.dump && rake stuff:update_users_password
# heroku pgbackups:capture --app instorem && curl -o latest.dump `heroku pgbackups:url --app instorem` && rake db:drop db:create && pg_restore --verbose --clean --no-acl --no-owner -h localhost -U postgresql -d instorem_server latest.dump && rake stuff:update_users_password

# heroku pg:backups restore 'https://dl.dropboxusercontent.com/u/34533306/instorem_server.dump' DATABASE -a instorem && heroku run rake stuff:update_users_password db:migrate db:seed --app instorem


# psql -U postgresql -d instorem_server < PostgreSQL.sql
# psql -U postgresql -d ism_staging < PostgreSQL.sql
# heroku pg:backups restore 'https://dl.dropboxusercontent.com/u/34533306/instorem_server.dump' DATABASE -a instorem